services:
  db:
    image: postgres:16-alpine
    container_name: pq_db
    restart: always
    env_file:
      - ./.env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - psql_crm:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1s
      retries: 5

  api:
    depends_on:
      db:
        condition: service_healthy
    container_name: go_api
    env_file:
      - ./.env
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      args:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_DB: ${POSTGRES_DB}
        API_PORT: ${API_PORT}
    ports:
      - ${API_PORT}:3001

volumes:
  psql_crm:
