// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Lead struct {
	ID        uuid.UUID
	Name      string
	Phone     sql.NullString
	CreatedAt time.Time
}
